{"status"=>"OK",
 "usage"=>
  "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
 "totalTransactions"=>"546",
 "result"=>
  {"docs"=>
    [{"id"=>"ODE4MjQ1NzAwNHwxNDU3MjQ4OTMw",
      "source"=>
       {"enriched"=>
         {"url"=>
           {"publicationDate"=>{"confident"=>"no", "date"=>"20160305T195100"},
            "title"=>"Saturday Night Vote-Ball Open Thread - Colorado Pols",
            "url"=>
             "http://coloradopols.com/diary/81284/saturday-night-vote-ball-open-thread"}}},
      "timestamp"=>1457248930},
     {"id"=>"NzE1NTcwODAzNXwxNDU3MTE2MDA4",
      "source"=>
       {"enriched"=>
         {"url"=>
           {"publicationDate"=>{"confident"=>"no", "date"=>"20160303T205000"},
            "title"=>"A Song for Donald Trump - Colorado Pols",
            "url"=>
             "http://coloradopols.com/diary/81253/a-song-for-donald-trump?utm_source=dlvr.it&utm_medium=twitter"}}},
      "timestamp"=>1457116008},
     {"id"=>"NzI3NjgyNDU4MnwxNDU3MDQ5NjAw",
      "source"=>
       {"enriched"=>
         {"url"=>
           {"publicationDate"=>{"confident"=>"yes", "date"=>"20160304T000000"},
            "title"=>"#CuresNow: “We must do better. And, we can.”",
            "url"=>
             "https://energycommerce.house.gov/news-center/news/curesnow-we-must-do-better-and-we-can"}}}
           }}
