default: &default

  adapter: postgresql
  encoding: unicode
  pool: 5
  #
  # host: localhost
  # username: legislators
  # password: <%= ENV['LEGISLATORS_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: legislators_development
  # username: legislators
  # password: <%= ENV['LEGISLATORS_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: legislators_test
  # username: legislators
  # password: <%= ENV['LEGISLATORS_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: legislators_production
  # username: legislators
  # password: <%= ENV['LEGISLATORS_DATABASE_PASSWORD'] %>
